project:
  type: website

website:
  title: "OECD Better Life Index 2024 Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Graphs
        menu:
          - href: graph-1.html
            text: Graph 1
          - href: graph-2.html
            text: Graph 2
      - href: sources.html
        text: Sources

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
