project:
  type: website

website:
  title: "OECD Better Life Index 2024 Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
        menu: 
          - href: graph-1.qmd
            text: Graph 1
          - href: graph-2.qmd
            text: Graph 2
      - href: graph-1.qmd
        text: "Graph #1"
      - href: graph-2.qmd
        text: "Graph #2"
      - text: "Sources"
        href: sources.html

format:
  html:
    theme: yeti
    css: styles.css
    toc: true


